services:
  i-got-bills-backend:
    build:
      context: .
      network: host
    container_name: i-got-bills-backend
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3001:3001"
    volumes:
      - /volume1/docker/i-got-bills-data:/data
    environment:
      - PORT=3001
      - APP_KEY=REPLACE_WITH_YOUR_KEY
      - DATA_DIR=/data
